name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        architecture: [x64]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Set runtime
      run: |
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          echo "DOTNET_RUNTIME=linux-x64" >> $GITHUB_ENV
        else
          echo "DOTNET_RUNTIME=win-x64" >> $GITHUB_ENV
          setx DOTNET_RUNTIME win-x64
        fi
    - name: Restore dependencies
      run: dotnet restore
    - name: Build projects
      run: dotnet build adoptiumjdk-sklauncher-installer.csproj --no-restore --runtime ${{ env.DOTNET_RUNTIME }}
    - name: Archive build files
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-files-${{ matrix.os }}-${{ matrix.architecture }}
        path: |
          **/bin/Debug/*
          **/bin/Release/*

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download build files
      uses: actions/download-artifact@v4
      with:
        name: build-files-${{ matrix.os }}-${{ matrix.architecture }}
        path: ./artifacts
    - name: Upload build files for download
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: ./artifacts
