name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        architecture: [x64]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Set runtime
      run: echo "DOTNET_RUNTIME=${{ matrix.os == 'ubuntu-latest' && 'linux-x64' || 'win-x64' }}" >> $GITHUB_ENV
    - name: Restore dependencies
      run: dotnet restore --runtime ${{ env.DOTNET_RUNTIME }}
    - name: Build
      run: dotnet build --no-restore --runtime ${{ env.DOTNET_RUNTIME }}
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Archive build files
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-files-${{ matrix.os }}-${{ matrix.architecture }}
        path: |
          **/bin/Debug/*
          **/bin/Release/*
