name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        architecture: [x64]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Set runtime
      run: echo "DOTNET_RUNTIME=${{ matrix.os == 'ubuntu-latest' && 'linux-x64' || 'win-x64' }}" >> $GITHUB_ENV
    - name: Restore dependencies
      run: dotnet restore
    - name: Build projects
      run: |
        for proj in $(find . -name '*.csproj'); do
          dotnet build $proj --no-restore --runtime ${{ env.DOTNET_RUNTIME }}
        done
    - name: Test projects
      run: |
        for proj in $(find . -name '*.csproj'); do
          dotnet test $proj --no-build --verbosity normal
        done
    - name: Archive build files
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-files-${{ matrix.os }}-${{ matrix.architecture }}
        path: |
          **/bin/Debug/*
          **/bin/Release/*
